apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sops-kms-test-prod
  namespace: argocd
  annotations:
    # resolves to the 'guestbook' directory
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  project: default
  source:
    path: main
    repoURL: https://github.com/vimweera/gitops-secrets.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - secrets://secrets/prod/values.yaml
  destination:
    namespace: sops-kms-test
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true