application:
    token: ENC[AES256_GCM,data:YhPenLUdMukwMTzvEoj2RQ==,iv:obmmaahuwhhH/emHC9aPHeR0qBo1EdYN/38St32nvPk=,tag:rrsBshU9NAymnIkP17LMTg==,type:str]
    siteType: production
    adminPassword: ENC[AES256_GCM,data:DSCQhF3hlqB1xYtS+oz/AnU=,iv:tlZWTQPo/ejP6PdTMVjp9hQDJS+Wyoi4AUtTdF00QII=,tag:yn1/QXEqFoDLa3PNoH9ggg==,type:str]
email:
    enabled: false
    host: ENC[AES256_GCM,data:57gEBjcdCj7dI0GBa2U=,iv:m25o0WXNc8RNHhcleC0wD83cA7iQxy+akIJ9MkqbwsY=,tag:b21mYdy+nAkvrLnNZCZJzA==,type:str]
    user: ENC[AES256_GCM,data:KFb97neLCA==,iv:H8P/ajpdL45ZDViaUGDYidngMbafKQksvTnFBjZXPWk=,tag:ggTsBI0npbTqEOhyYXCW5A==,type:str]
    password: ENC[AES256_GCM,data:WTRj2WfK2kQl,iv:RVI12LND/tZlDF5+7xwS2i34DjAvnqDiVyWC6vZ3c6U=,tag:+TSEbkgY8Hn5Igz8MvDK6A==,type:str]
ingress:
    domain: ruwanvm.com
    certificateArn: arn:aws:acm:us-south-2:123456789099:certificate/rstuvwxyz1234567890abcdefghijklmnopq
database:
    rootUser: ENC[AES256_GCM,data:7mGxowArz6E=,iv:gJNLYhB2w+KcpmzGxlBMU30edtdCmPOTPbxIeD4Tuv8=,tag:XSVali40QG8hUpM65nbTIQ==,type:str]
    rootPassword: ENC[AES256_GCM,data:AfqOyxjuGL4BH1q4t6ppoZlk589+fdy35YspQAz+0LbSFfmq,iv:yUi4h/ZlMUIUhNoqlYIqHXTuqZZz3D3HsE25L2cNQF4=,tag:1wwfVNG3U2n/15uuKSh0Tw==,type:str]
    name: ruwanvm-db
    user: ENC[AES256_GCM,data:Wx045u9nm8Ev/NgzNl+J,iv:acaMBjLDnT0kUR4BqEe1wUBz6+zg3qtql6oyEnC3qlA=,tag:g9G8Tgv/HmGj3Pr1DvOseQ==,type:str]
    host: ENC[AES256_GCM,data:UQE8kjoZeN6/dNswRJfJAJrCs36vcGw14T9P4aNfnzaUZss7iLbqfhoRVAIg1XVFY+uDxtje,iv:UQRqLKyUqSPoCVnl042+F6Cj8Nt1lBnRvXF0V+tLWQM=,tag:ZiziH03eYbES3WtmoPngeQ==,type:str]
    password: ENC[AES256_GCM,data:zVBZW0pdFHoNEeZ1aaaMM5s8AQQ/dM0E,iv:ocXYxuzPnWT23VKcXD+MIDtRXrSm0/2atzen72DqjxE=,tag:fC7olfZvYD78c/mzOzOhwQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-southeast-2:473711392723:key/6931c86b-9248-4681-9c75-2368337dd48a
          created_at: "2023-06-22T03:18:12Z"
          enc: AQICAHg2Q/cpSs1YtkV+L2AxFnE+kUcJ5xZxW9PCQT2NfREECAH5mofKH5QK2YG3u9yE/kVhAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMzPclRpU5x3a/ubkrAgEQgDv0R6sLv5vIT09Sc24iY1oVPnE2zPUmpGF/JyYbJUyX2JnZFmBSlgmoGwq+HBEfreSiVE7gwwyIGVNccA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-06-22T03:18:13Z"
    mac: ENC[AES256_GCM,data:XRbtvWv4hIuwGbBAIZgF5Rm9z5b/dfHMdzdodZIPT4YgszW6AostaA1uo5fkuiA98KUk9CxPXfYRx33Ij/CKPiS/3ncoNQ5hS0D2nc5h8qrXAuHrYGEsAfOF/phzhoNPp6RPJpE8XsPrRyI9bKmvl28cDAr3baaHpghGNfE3rCo=,iv:TKLWlE1IWqaBh9u18d7T3c1uWJvyq6+por52lsuV7eg=,tag:CAc255kA5CJFYVnTT3wqGA==,type:str]
    pgp: []
    encrypted_regex: (?:^token$|(?i).*password|^host|(?i).*user)
    version: 3.7.3
