application:
    token: ENC[AES256_GCM,data:8izYgLxRbyrgHBs=,iv:+DsVnYiuKRtx93icaiuOcVhTDfwwh4UlUxp6ssdulsI=,tag:t+8azTpDAFObg8bhV9SqHQ==,type:str]
    siteType: local-development
    adminPassword: ENC[AES256_GCM,data:aOeT/+gKnxG55rot/qfDV6E=,iv:QLUWxOpYu7zH+wCe9LabGjeO6ebZpwXCTx4+ZcQFsw8=,tag:qmRwvYSxCgtmTkfyQrjuLQ==,type:str]
email:
    enabled: false
    host: ENC[AES256_GCM,data:9mvV+uy+rxHa+OQMot4=,iv:Y3kObQZm6kUqE0nnnODKPr0qg8SezVrzFUsILU15Lng=,tag:5iVwF2r3okaXeSLHyNWdEg==,type:str]
    user: ENC[AES256_GCM,data:q+3zRBal0A==,iv:Z7z6ievyNr8AVbzn4kmLSpua4dKP+nM3JliNoaJknBM=,tag:S604z1u8ykyt++ceS+pCcQ==,type:str]
    password: ENC[AES256_GCM,data:J0GxgzMEtyZq,iv:b23Avr91N1CW+MHNMo3E1NNkuijfM9jSVdE08ZbOIJ8=,tag:1Jth1b76ORF+D5ZznJ5SZA==,type:str]
ingress:
    domain: ruwanvm.com
    certificateArn: arn:aws:acm:us-south-2:123456789099:certificate/rstuvwxyz1234567890abcdefghijklmnopq
database:
    rootUser: ENC[AES256_GCM,data:SKZFc4sdSl0=,iv:yeLazxuFzeou1VdIQLi1oCOS2UNVKCzvjwMauctRiHk=,tag:Cuqen0XzyPpCCfnGRzCi2Q==,type:str]
    rootPassword: ENC[AES256_GCM,data:jcWNEVnmFbaTCQLfmgnvELs5UI0x07HfFgoK2IK3dLLai9LY,iv:Spngg5BxF3FLIVbstxgZ5YPuzDsvm9sI4nhw3PMERrc=,tag:uigOAnS99jb42Gsb8nLy9A==,type:str]
    name: ruwanvm-db
    user: ENC[AES256_GCM,data:6T7Fy5HdPsnzq9Mz4BZJ,iv:AHCfKuE0xDGQ/GdBTkIZt2NpWU3aHs2is11foKYIAcs=,tag:rxSunplPYTV31eeY/Cwvqw==,type:str]
    host: ENC[AES256_GCM,data:wZG31kfjnVUMzlEFBBvEbz5+YX+i+ER8xruIHoCQNC9REx34z5zQoF8f0bhg73kQZZTJCaUa,iv:qSplGnNQ4KPBld0DkiSCaAhsPRwiZINJaZI7DcTtlY0=,tag:aPKSX8qVjAInSXBu7XYYFg==,type:str]
    password: ENC[AES256_GCM,data:lcLZNGRQ4k2FBsTw7bKursmkBG+LyCaR,iv:9jSCuK0yrzrGUDZZDyHyaSnIh37NI4t+7efp0++sO7A=,tag:1bt4g+FyTcW+WA3onuTIQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-06-22T03:18:34Z"
    mac: ENC[AES256_GCM,data:H9XCT44oRDriDbvk3NsVX6wqvdtW09Z5I8dibGbMYPr8gxkQuIUCN+lYP1AL7buDONzcL/LKa7gCC9SgbJLFrkLhE3kSOg70KxbNr/+6AvefzbdoEGfkb6TYzOpBd1PMgSL7DWGJU0PHgYfkqolP9SmEgcbHSEFNnba/PJ8onn8=,iv:Lesfx2T9KP9+zcf8IPeduWavQH6vRsLsMjXbFICqsA0=,tag:lWFzvRbHecgWNE+sQNwEeA==,type:str]
    pgp:
        - created_at: "2023-06-22T03:18:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA79Nx+PIVfL0AQ/+P6UHRffbwBtiDmgFctgfuiiuQR6CPOtJ5bB+YecpL8BY
            2miivc9V2dif2P6+ys9ojmPPRP3KR1sW7l6md/xIlqH4mfQLjiS0AW19hbH3snh5
            rTb77iLCNCZgWpz1nKmqm4L4F2XZQ/9h1WRTPmIKnCwfAkqsIyq9bUpS381KE1fk
            WAwhM6LzPFxbVCp46PUnFq/VtzO8nEiT4CpH7u7jrqETJytuGPGoJu74DrBTFfXA
            Bl2bGiCcWesPcWlSHvaBOco3eDpuOt1YNy/Y8xvVVjbURJaWJFFpDQ9+EgLdF6JJ
            fe0oQW/B9Kkbi4lwowz8rr1M+EJGcu/nRA1DF7LYGRaAv7+yyYiulZcBnpH8e8aK
            YQUZ9Qt7fBh4fHG96wkx119uWbmD/nSCstf/C0inf8GmCRHKMKsBoFYvbrM4/u4o
            xV3fRt9vMRsPomlh2L+VPQF7WxD2wR9RIZPIHuUFFw5VmpQNwDXgqqPXdN17tHCR
            9v6t18gLal0Cqh9EvknrSoaB9VTbXFjy6JZlwgX/nhaRNwjcxbNODWQX0EtCEuwQ
            /WKUcJHECt4hUQw1LBLo+MnRmAUPwD/LaxfgFkI1ItG+oGrHBApSO+23VwvNgVXX
            lRCxLrzFsdlzpADnl8lwnTBVYbdcn1odgpiUwJAkRRk5SkJPEM1XrCFDUHqnL2rU
            aAEJAhCS9luCySAm/HlxmuQkP+++aUIi0v0S+VZzFkBPqXPULMuqp30nimH5hVd1
            Oh0shBJVlIcLqA69zQup50gAQp9mIWx4om2kV3qk5EASnSnSX5Oc7vNt1Juob1dl
            p619QJnXX2Om
            =30HA
            -----END PGP MESSAGE-----
          fp: 17C627E5ACD7DB3DBF1CD6F931C5F7B209E2A866
    encrypted_regex: (?:^token$|(?i).*password|^host|(?i).*user)
    version: 3.7.3
